/*
------------------------------------------------
Generated by Cradle 2.0.2.0
https://github.com/daterre/Cradle

Original file: Story.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Story: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("thoughts_taught", () => this.@thoughts_taught, val => this.@thoughts_taught = val);
			VarDef("stats_taught", () => this.@stats_taught, val => this.@stats_taught = val);
			VarDef("ending_1_completed", () => this.@ending_1_completed, val => this.@ending_1_completed = val);
			VarDef("ending_2_completed", () => this.@ending_2_completed, val => this.@ending_2_completed = val);
			VarDef("ending_3_completed", () => this.@ending_3_completed, val => this.@ending_3_completed = val);
		}

		public StoryVar @thoughts_taught;
		public StoryVar @stats_taught;
		public StoryVar @ending_1_completed;
		public StoryVar @ending_2_completed;
		public StoryVar @ending_3_completed;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Macros macros1;
	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros2;

	@Story()
	{
		this.StartPassage = "Prologue";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Macros() { Story = this };
		macros2 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Prologue

	void passage1_Init()
	{
		this.Passages[@"Prologue"] = new StoryPassage(@"Prologue", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		macros1.playMusic("myuu-Memento");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("I hate my life.");
		yield return lineBreak();
		macros1.showImage("vincent");
		yield return lineBreak();
		yield return text("I am 21 years old. My name is Vincent...");
		yield return lineBreak();
		yield return text("and this is my story.");
		yield return lineBreak();
		macros1.hideImage();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("I grew up in a big city in Italy.");
		yield return lineBreak();
		yield return text("I enjoyed the easy life, not caring about school. Not caring about friends, or an" +
		    "ything.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Heeehhh.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("I soon had to make a choice.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("After secondary school", "PrologueUniversity", null);
		yield break;
	}


	// .............
	// #2: PrologueUniversity

	void passage2_Init()
	{
		this.Passages[@"PrologueUniversity"] = new StoryPassage(@"PrologueUniversity", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		if(Vars.thoughts_taught==0) {
			macros1.showText("You influenced Vincent\'s thoughts.");
			Vars.thoughts_taught = 1;
		}
		yield return lineBreak();
		yield return text("After I finished secondary school,");
		yield return lineBreak();
		yield return text("I had to decide what I was going to do with my life.");
		yield return lineBreak();
		yield return text("University.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("I was afraid", "PrologueUniversity2", null);
		yield return lineBreak();
		yield return link("My childhood dream", "PrologueHobbies", null);
		yield break;
	}


	// .............
	// #3: PrologueUniversity2

	void passage3_Init()
	{
		this.Passages[@"PrologueUniversity2"] = new StoryPassage(@"PrologueUniversity2", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		macros1.setDM("Afraid");
		yield return lineBreak();
		if(Vars.stats_taught==0) {
			macros1.showText("You influenced Vincent\'s mood.");
			Vars.stats_taught = 1;
		}
		yield return lineBreak();
		yield return text("I was afraid.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("My life was going down. Everyone else knew what they wanted to do, everyone");
		yield return lineBreak();
		yield return text("but me.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("So I picked", "PrologueUniChoice", null);
		yield break;
	}


	// .............
	// #4: PrologueHobbies

	void passage4_Init()
	{
		this.Passages[@"PrologueHobbies"] = new StoryPassage(@"PrologueHobbies", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		macros1.setDM("Nostalgic");
		yield return lineBreak();
		if(Vars.stats_taught==0) {
			macros1.showText("You influenced Vincent\'s mood.");
			Vars.stats_taught = 1;
		}
		yield return lineBreak();
		yield return text("My childhood dream has always been to become a rock star.");
		yield return lineBreak();
		yield return text("I was dreaming I\'d be famous...");
		yield return lineBreak();
		yield return text("and...");
		yield return lineBreak();
		yield return text("well, that doesn\'t matter. I could never be famous.");
		yield return lineBreak();
		yield return text("I\'m not talented.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("I was scared about University.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("So I picked", "PrologueUniChoice", null);
		yield break;
	}


	// .............
	// #5: PrologueUniChoice

	void passage5_Init()
	{
		this.Passages[@"PrologueUniChoice"] = new StoryPassage(@"PrologueUniChoice", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("So I picked Computer Science!");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("I enjoyed video games, a lot. I\'d play hours and hours, day and night.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("And I did some programming in school.");
		yield return lineBreak();
		yield return text("I thought that was it. I was going to be a programmer.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Well", "ProloguePunchline", null);
		yield break;
	}


	// .............
	// #6: ProloguePunchline

	void passage6_Init()
	{
		this.Passages[@"ProloguePunchline"] = new StoryPassage(@"ProloguePunchline", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		macros1.setDM("Angry");
		yield return lineBreak();
		if(Vars.stats_taught==0) {
			macros1.showText("You influenced Vincent\'s mood.");
			Vars.stats_taught = 1;
		}
		yield return lineBreak();
		yield return text("I quit. I couldn\'t stand it.");
		yield return lineBreak();
		yield return text("I\'m not good at programming.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Not good at anything.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("I\'m poor, \'have no money.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("What am I going to do?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("No one cares about me", "ProloguePlNeg", null);
		yield return lineBreak();
		yield return link("Maybe there is hope", "ProloguePlPos", null);
		yield return lineBreak();
		yield return link("What if I do get a job", "ProloguePlPos", null);
		yield break;
	}


	// .............
	// #7: ProloguePlNeg

	void passage7_Init()
	{
		this.Passages[@"ProloguePlNeg"] = new StoryPassage(@"ProloguePlNeg", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("No one...");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("It hurts.");
		yield return lineBreak();
		macros1.setDM("Very Sad");
		yield return lineBreak();
		yield return text("I\'ll just go to sleep.");
		yield return lineBreak();
		yield return link("zzz", "WakeUp_Neg_D1", null);
		yield break;
	}


	// .............
	// #8: ProloguePlPos

	void passage8_Init()
	{
		this.Passages[@"ProloguePlPos"] = new StoryPassage(@"ProloguePlPos", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("Yeah... maybe...");
		yield return lineBreak();
		yield return text("I could get a job. I shouldn\'t lose hope.");
		yield return lineBreak();
		macros1.setDM("Hopeful");
		yield return lineBreak();
		yield return text("I\'ll go to sleep now.");
		yield return lineBreak();
		yield return link("zzz", "WakeUp_Neg_D1", null);
		yield break;
	}


	// .............
	// #9: WakeUp_D1

	void passage9_Init()
	{
		this.Passages[@"WakeUp_D1"] = new StoryPassage(@"WakeUp_D1", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		macros1.stopMusic();
		yield return lineBreak();
		macros1.playSound("snoring");
		yield return lineBreak();
		macros1.elvesExeShowJobAdvert();
		yield return lineBreak();
		macros1.protagonistWakeUp();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		macros1.stopSound();
		yield return lineBreak();
		yield return text("Oh... whoah. Hmm.");
		yield return lineBreak();
		yield return text("What is this?");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Oh, I can\'t believe this!");
		yield return lineBreak();
		yield return text("It\'s perfect...");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("I have finally found the meaning of life.");
		yield return lineBreak();
		Vars.ending_1_completed = 1;
		yield return lineBreak();
		Vars.ending_2_completed = 0;
		yield return lineBreak();
		Vars.ending_3_completed = 0;
		yield return lineBreak();
		macros1.showGameOver("Vincent has found the meaning of life. Congrats!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("l" + 1, "l1", null);
		yield return lineBreak();
		yield return link("l" + 2, "l2", null);
		yield break;
	}


	// .............
	// #10: WakeUp_Neg_D1

	void passage10_Init()
	{
		this.Passages[@"WakeUp_Neg_D1"] = new StoryPassage(@"WakeUp_Neg_D1", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		macros1.stopMusic();
		yield return lineBreak();
		yield return lineBreak();
		macros1.playSound("snoring");
		yield return lineBreak();
		yield return lineBreak();
		macros1.showImage("bed");
		yield return lineBreak();
		yield return text("delay 2.0");
		yield return lineBreak();
		macros1.hideImage();
		yield return lineBreak();
		yield return text("delay 1.5");
		yield return lineBreak();
		macros1.playSound("coffee-machine");
		yield return lineBreak();
		macros1.showImage("coffee-machine");
		yield return lineBreak();
		yield return text("delay 2.0");
		yield return lineBreak();
		macros1.playSound("coffee-drinking");
		yield return lineBreak();
		macros1.hideImage();
		yield return lineBreak();
		yield return text("delay 1.0");
		yield return lineBreak();
		macros1.stopSound();
		yield return lineBreak();
		macros1.showImage("sunrise");
		yield return lineBreak();
		yield return text("delay 1.0");
		yield return lineBreak();
		yield return text("Huh. What a night.");
		yield return lineBreak();
		yield return lineBreak();
		macros1.hideImage();
		yield return lineBreak();
		yield return text("delay 1.0");
		yield return lineBreak();
		macros1.setSH("Tired");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("What to do today...");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Oh there\'s this new game, Rocket League");
		yield return lineBreak();
		yield return text("Yeah, let\'s have some fun");
		yield return lineBreak();
		macros1.showImage("rocket-league");
		yield return lineBreak();
		macros1.playSound("rocket-league-gameplay");
		yield return lineBreak();
		yield return text("delay 3.0");
		yield return lineBreak();
		macros1.stopSound();
		yield return lineBreak();
		yield return text("Ah, darn it! I lost again.");
		yield return lineBreak();
		macros1.hideImage();
		yield return lineBreak();
		yield return text("Stupid game, who made it...");
		yield return lineBreak();
		yield return lineBreak();
		macros1.showImage("mcd-food");
		yield return lineBreak();
		yield return text("Lunch time. MMmmm.");
		yield return lineBreak();
		macros1.playSound("eating");
		yield return lineBreak();
		yield return text("delay 1.0");
		yield return lineBreak();
		macros1.hideImage();
		yield return lineBreak();
		macros1.stopSound();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Rocket League... maybe I can hack it!");
		yield return lineBreak();
		macros1.setDM("Excited");
		yield return lineBreak();
		yield return lineBreak();
		macros1.showImage("google");
		yield return lineBreak();
		macros1.playSound("typing");
		yield return lineBreak();
		yield return text("delay 2.0");
		yield return lineBreak();
		macros1.showImage("hack-tool");
		yield return lineBreak();
		macros1.stopSound();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Yeah, this could work");
		yield return lineBreak();
		yield return lineBreak();
		macros1.showImage("rocket-league");
		yield return lineBreak();
		macros1.playSound("rocket-league-gameplay");
		yield return lineBreak();
		yield return text("delay 2.0");
		yield return lineBreak();
		macros1.stopSound();
		yield return lineBreak();
		macros1.setDM("Aggressive");
		yield return lineBreak();
		yield return text("Woho, bite the dust, losers!");
		yield return lineBreak();
		macros1.hideImage();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Hacking this was fun. If only programming was this fun. Maybe I wouldn\'t have dro" +
		    "pped out");
		yield return lineBreak();
		macros1.setDM("Sad");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Back to the real life...");
		yield return lineBreak();
		yield return text("I spent another day. Playing. Oh, it\'s the 25th. My rent is due soon.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("What am I gonna do. What am I gonna do. What am I gonna do. What am I gonna do");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("I am gonna die", "Die1", null);
		yield return lineBreak();
		yield return link("I think it is going to be okay", "OkFindGDD", null);
		yield break;
	}


	// .............
	// #11: Die1

	void passage11_Init()
	{
		this.Passages[@"Die1"] = new StoryPassage(@"Die1", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		macros1.setDM("Depressive");
		yield return lineBreak();
		macros1.playMusic("myuu-Memento");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("No...");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Yes...");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("No...");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("I have to.");
		yield return lineBreak();
		yield return lineBreak();
		macros1.setSH("Bleeding");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		macros1.playSound("crying");
		yield return lineBreak();
		macros1.showImage("death");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		macros1.hideImage();
		yield return lineBreak();
		Vars.ending_3_completed = 1;
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		macros1.showGameOver("Vincent could not stand it anymore and decided it is just easier to quit life.");
		yield break;
	}


	// .............
	// #12: OkFindGDD

	void passage12_Init()
	{
		this.Passages[@"OkFindGDD"] = new StoryPassage(@"OkFindGDD", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		macros1.playMusic("myuu-Memento");
		yield return lineBreak();
		yield return text("It is ok. I am ok. I can find a way. Really");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("I am alone. But. I do not need anyone. I can live another day.");
		yield return lineBreak();
		yield return text("Come on, Vincent!");
		yield return lineBreak();
		yield return lineBreak();
		macros1.setDM("Calm");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Maybe the night will fix my bugs.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("zZzZzZ", "GDDNight", null);
		yield break;
	}


	// .............
	// #13: GDDNight

	void passage13_Init()
	{
		this.Passages[@"GDDNight"] = new StoryPassage(@"GDDNight", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		macros1.stopMusic();
		yield return lineBreak();
		macros1.playSound("snoring");
		yield return lineBreak();
		macros1.showImage("night");
		yield return lineBreak();
		yield return text("delay 1.0");
		yield return lineBreak();
		macros1.hideImage();
		yield return lineBreak();
		yield return text("delay 1.0");
		yield return lineBreak();
		macros1.stopSound();
		yield return lineBreak();
		macros1.playSound("elves");
		yield return lineBreak();
		macros1.showImage("elves");
		yield return lineBreak();
		macros1.showText("elves.exe in progress...");
		yield return lineBreak();
		yield return text("delay 1.0");
		yield return lineBreak();
		macros1.hideImage();
		yield return lineBreak();
		yield return text("delay 1.0");
		yield return lineBreak();
		macros1.showImage("unity");
		yield return lineBreak();
		yield return text("delay 1.0");
		yield return lineBreak();
		macros1.hideImage();
		yield return lineBreak();
		yield return text("delay 1.0");
		yield return lineBreak();
		macros1.showImage("vstudio");
		yield return lineBreak();
		yield return text("delay 1.0");
		yield return lineBreak();
		macros1.hideImage();
		yield return lineBreak();
		yield return text("delay 3.0");
		yield return lineBreak();
		macros1.playSound("coffee-machine");
		yield return lineBreak();
		macros1.showImage("coffee-machine");
		yield return lineBreak();
		yield return text("delay 2.0");
		yield return lineBreak();
		macros1.playSound("coffee-drinking");
		yield return lineBreak();
		macros1.hideImage();
		yield return lineBreak();
		yield return text("delay 1.0");
		yield return lineBreak();
		macros1.stopSound();
		yield return lineBreak();
		macros1.showImage("sunrise");
		yield return lineBreak();
		yield return text("delay 1.0");
		yield return lineBreak();
		yield return text("Hey. This night was better!");
		yield return lineBreak();
		macros1.hideImage();
		yield return lineBreak();
		macros1.setSH("Rested");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Let\'s open the computer...");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("What the");
		yield return lineBreak();
		macros1.setDM("Surprised");
		yield return lineBreak();
		macros1.showImage("unity");
		yield return lineBreak();
		yield return text("Wha. Uni-tee? Unity? What is this");
		yield return lineBreak();
		yield return lineBreak();
		macros1.playSound("keyboard");
		yield return lineBreak();
		macros1.showImage("google");
		yield return lineBreak();
		macros1.stopMusic();
		yield return lineBreak();
		yield return text("delay 1.0");
		yield return lineBreak();
		yield return text("Oh, I see. Game development platform... like what I used yesterday! Kind of");
		yield return lineBreak();
		macros1.hideImage();
		yield return lineBreak();
		yield return text("Maybe I can create games. Yeah, yeah. Good idea");
		yield return lineBreak();
		macros1.setDM("Motivated");
		yield return lineBreak();
		yield return lineBreak();
		macros1.showImage("inception");
		yield return lineBreak();
		yield return text("Oh I know! I\'ll make a game about a musician. Yes, a rock player");
		yield return lineBreak();
		yield return text("He was in a band, but quit because he was fighting with his mates");
		yield return lineBreak();
		yield return text("And when he was little he wanted to be a programmer");
		yield return lineBreak();
		macros1.hideImage();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("I\'ll be a game programmer. A... no, a game designer!");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("I wonder what that elves.exe program was... and why did it help me?");
		yield return lineBreak();
		yield return lineBreak();
		Vars.ending_1_completed = 1;
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		macros1.showGameOver("Vincent found out he actually likes programming, just a bit differently. Those ga" +
		    "mes were, after all, good for him.");
		yield return lineBreak();
		macros1.playSound("happy-end");
		yield break;
	}


	// .............
	// #14: l1

	void passage14_Init()
	{
		this.Passages[@"l1"] = new StoryPassage(@"l1", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #15: l2

	void passage15_Init()
	{
		this.Passages[@"l2"] = new StoryPassage(@"l2", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}